# Generated by Django 2.0.4 on 2018-05-01 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFromParsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('charset', models.CharField(blank=True, max_length=10)),
                ('h1', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='URLForProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('timeshift', models.DurationField(blank=True, help_text='After how many time process parsing this url will be started. Enter empty value if you want fast start processing.', null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'wait'), (2, 'processing'), (3, 'success'), (4, 'error')], default=1, verbose_name='Operation status')),
                ('start_processing', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='resultfromparsing',
            name='url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.URLForProcessing'),
        ),
    ]
