# Generated by Django 2.0.4 on 2018-05-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlforprocessing',
            name='start_processing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
