# Generated by Django 2.0.4 on 2018-05-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180501_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('status_cron', models.PositiveSmallIntegerField(choices=[(1, 'wait'), (2, 'process')], default=1)),
            ],
        ),
    ]
